package com.rsetiapp.common.model.request


data class InsertSdrVisitReq(
    val appVersion: String,
    val login: String,
    val imeiNo: String,
    val instituteId: Int,
    val financialYear: String,
    val monthCode: Int,
    val cleanlinessMaintained: String,
    val cleanlinessMaintainedImage: String,
    val cleanlinessMaintainedLat: String,
    val cleanlinessMaintainedLong: String,
    val isSignboardDisplayed: String,
    val signboardDisplayedImage: String,
    val signboardDisplayedImageLat: String,
    val signboardDisplayedImageLong: String,
    val isTimeTableDrawn: String,
    val timeTableDrawnImage: String,
    val timeTableDrawnImageLat: String,
    val timeTableDrawnImageLong: String,
    val isTimeTableOngoingTrainingProgramDisplayed: String,
    val timeTableOngoingTrainingProgramDisplayedImage: String,
    val timeTableOngoingTrainingProgramDisplayedImageLat: String,
    val timeTableOngoingTrainingProgramDisplayedImageLong: String,
    val areActionPhotosDisplayed: String,
    val actionPhotosDisplayedImage: String,
    val actionPhotosDisplayedImageLat: String,
    val actionPhotosDisplayedImageLong: String,
    val isSuccessStoriesInLocalLanguageDisplayed: String,
    val successStoriesInLocalLanguageDisplayedImage: String,
    val successStoriesInLocalLanguageDisplayedImageLat: String,
    val successStoriesInLocalLanguageDisplayedImageLong: String,
    val isOfficeTimingDisplayed: String,
    val officeTimingDisplayedImage: String,
    val officeTimingDisplayedImageLat: String,
    val officeTimingDisplayedImageLong: String,
    val isTrainingKitAvailable: String,
    val trainingKitAvailableImage: String,
    val trainingKitAvailableImageLat: String,
    val trainingKitAvailableImageLong: String,
    val isEDPInputsInLocalLanguageAvailable: String,
    val eDPInputsInLocalLanguageAvailableImage: String,
    val eDPInputsInLocalLanguageAvailableImageLat: String,
    val eDPInputsInLocalLanguageAvailableImageLong: String,
    val isServedFoodDetailsDisplayed: String,
    val servedFoodDetailsDisplayedImage: String,
    val servedFoodDetailsDisplayedImageLat: String,
    val servedFoodDetailsDisplayedImageLong: String
)

